### ISSUE TITLE
Transferring funds to non-existing or pre-compiled addresses 

### ISSUE THREAD

**Issue by Petyo-Lukanov** [LimeChain/hedera-services#341]
Verify that no interaction causes the creation of a new Hedera Account, f.e creating new account when transferring funds to it through TX.

Keep in mind that Hedera account of type `isSmartContract=true` can be created through Transaction (smart contract factory design pattern)

**Comment by Daniel-K-Ivanov** [comment]
@alshapi to schedule a call tmr late in the day to run us through the hedera master implementation and propose a solution for our integration

**Comment by Daniel-K-Ivanov** [comment]
Guides and steps for the successful implementation of the task:

1. We cannot let the transaction be processed and halt/revert it once we get to the commit step due to several reasons:
 - It will be expensive to execute the whole transaction just to revert it in the end on commit even though the transaction reached "invalid" account access at the start.
 - If we reach "invalid" account access, we must trigger an `ExceptionalHalt` and stop the processing otherwise we risk the `storagekeys` or other state updates to be committed at the end. The only state update must be the gas charges of the sender if the transaction accesses non-existing account.

Practical implementation steps:
1. Go through the `MainnetTransactionProcessor` and see every place where we are reading the account. We must ensure that if `null` account is returned **and the account is not contract** - revert with ExceptionalHalt - INVALID_SOLIDITY_ADDRESS reason
2. Go through all `opcodes` in the EVM and compile a list of opcodes that can either access or create accounts (example opcodes are `CALL`/ `DELEGATECALL`/`CREATE`/`CREATE2`)
3. For each OPCODE we must change the implementation such that if non existing account is called/created we must throw exceptional halts
