### ISSUE TITLE
HSCS-THR-001-005

### ISSUE THREAD

**Issue by stoqnkpL** [LimeChain/hedera-services#681]
- [ ] HSCS-THR-001	Throttling 350/N contract calls per second where N is the number of nodes in the network, per node (pre-check)
- [ ] HSCS-THR-002	Throttling 350 contract calls per second throttle during handle transaction
- [ ] HSCS-THR-003	Throttling 15M gas/sec per node regardless of the number of nodes in the network (pre-check) based on reservation
    - Test large contracts (1-5m)
    - test small contracts
    - Test mix of large/small and check for greedy bin packing, for example, with 13 M reserved reject a 4M contract but accept multiple 400K contracts
- [ ] HSCS-THR-004	Throttling15M gas/sec for the network at handle transaction based on usage
    - Test large TXes filling up (1m-5m)
    - Test Small TXes filling up (40k gas)
    - Test large and small, and look for "greedy" bin packing behavior (eg with 3M left a 5M tx is rejected but multiple 400k TXes are rejected)
- [ ] HSCS-THR-005	SC calls are rejected if reserved gas is over the per tx gas limit (5M max gas) per contract call/create (pre-check)

**Comment by Petyo-Lukanov** [comment]
**General FYI:**
Tests are covered. 
There are 2 cases missing, where mixed transactions are being throttled with (e.g.) 1000 gas and others with (e.g.) 200 gas. Ideally we will be able to make sure that no transactions are blocked due to the others, but it's currently challenging to assert, when and which transactions exactly passed.

**PR:** https://github.com/hashgraph/hedera-services/pull/2453
